# Used by: Anyone requesting a new repository
name: "New Repo Request" # this shows on the chooser screen
description: Request creation of a new GitHub Repository # subtitle
labels: ["create-repo"] # this triggers the workflow
body:
  - type: input # plain text box
    id: repo-name # referenced as issueparser_repo-name in workflow
    attributes:
      label: Repo name # what the user sees
      placeholder: "my-new-repo"  # hint text inside the box
    validations:
      required: true # can't submit without filling this in

  - type: input
    id: description
    attributes:
      label: Description
      placeholder: "What is this repo for?"
    validations:
      required: true

  - type: dropdown
    id: visibility
    attributes:
      label: Visibility
      options:
        - private
        - public
    validations:
      required: true

  - type: input
    id: team
    attributes:
      label: Team
      placeholder: "e.g. Frontend Team"
    validations:
      required: true

  - type: input
    id: stack
    attributes:
      label: Stack
      placeholder: "e.g. React, Vue, Next.js"
    validations:
      required: true
